# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           /article/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:            Nathan Leung
tagline:          'Blog'
description:      'Lead Web Developer at <a href="https://www.leungenterprises.com">Leung Enterprises</a>'
baseurl:          /

author:
  name:           'Nathan Leung'
  url:            https://nathan.leun.ga/

paginate:         5

gems:
  - jekyll-sitemap

# Custom vars
version:          1.1.0


github:           https://github.com/nathanhleung
linkedin:         https://linkedin.com/in/nathanhleung
twitter:          https://twitter.com/nathanhleung
