# Dependencies
highlighter:      rouge

# Permalinks
permalink:           /article/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:            Nathan Leung
tagline:          'Blog'
description:      'Student, among other things'
baseurl:          /

author:
  name:           'Nathan Leung'
  url:            https://www.nathanhleung.com

paginate:         5

gems:
  - jekyll-sitemap

# Custom vars
version:          1.1.0


github:           https://github.com/nathanhleung
linkedin:         https://linkedin.com/in/nathanhleung
twitter:          https://twitter.com/nathanhleung
