# Dependencies
highlighter:      rouge

# Permalinks
permalink:           /article/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:            Nathan Leung
tagline:          'Blog'
description:      'Node.js/Angular/ES6'
baseurl:          /

author:
  name:           'Nathan Leung'
  url:            https://www.nathanhleung.com
  twitter:        nathanhleung

paginate:         5

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  
# seo tag vars
twitter:
  username: nathanhleung

# Custom vars
version:          1.1.0


github:           https://github.com/nathanhleung
linkedin:         https://linkedin.com/in/nathanhleung
